export enum PlayerStateEnum {
  PLAYING = 'PLAYING',
  LOADED = 'LOADED',
  STOPPED = 'STOPPED',
  LOADING = 'LOADING',
  PAUSED = 'PAUSED',
  ENDED = 'ENDED',
  BUFFERING = 'BUFFERING',
  SEEKING = 'SEEKING',
  RELOADING = 'RELOADING',
}
